server:
  port: 9000

spring:
  application:
    name: spring-data-jpa
  datasource:
    #MySQL database connection
    mysql:
      url: jdbc:mysql://localhost:3306/spring_data_jpa
      username: root
      password: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
    #Postgresql database connection
    postgres:
      url: jdbc:postgresql://localhost:5432/spring_data_jpa
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    generate-ddl: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
